### ISSUE TITLE
SecStr does not roundtrip with JSON

### ISSUE THREAD

**Issue by jfbilodeau** [myfreeweb/secstr#14]
Thanks for the SecStr library. I sorry, but I suspect I stumbled on a problem.

The following example fails when serializing a `SecStr` to and from JSON:

```rust
use secstr::SecStr;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct Account {
    username: String,
    password: SecStr,
}

fn main() {
    let account = Account {
        username: "test".to_string(),
        password: SecStr::from("password".as_bytes()),
    };

    let json = serde_json::to_value(account).unwrap();

    let account = serde_json::from_value::<Account>(json).unwrap();

    println!("done!");
}
```
When executing the code:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: sequence, expected a byte array", line: 0, column: 0)', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: secstr_roundtrip::main
             at src/main.rs:18
  17: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  21: std::panicking::try
             at src/libstd/panicking.rs:265
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  24: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

Cargo.toml:

```toml
[package]
name = "secstr-roundtrip"
version = "0.1.0"
authors = ["J-F Bilodeau <jfbilodeau@chronogears.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
secstr = { version = "0.3.2", features = ["serde"] }
```

I've tested the same behaviour with BSON and it roundtrips no problem. Also `SecUtf8` roundtrips fine with JSON.

Thanks,

J-F

**Comment by myfreeweb** [comment]
JSON is not a binary format, so you have to use some encoding. See https://github.com/serde-rs/serde/issues/661 for an example of using base64.

For a password, maybe you should just use `SecUtf8` indeed :)

**Comment by jfbilodeau** [comment]
You are correct. My bad!
